In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

In [211]:
all_files = os.listdir(path)
for x in data_files:
os.system(gunzip x)

/Users/bradleysawyer/fis/project1/project-description/zippedData

In [213]:
cd ..

/Users/bradleysawyer/fis/project1/project-description

In [173]:
path = '/Users/bradleysawyer/fis/project1/project-description/zippedData'
folder_files = os.listdir(path)
folder_files
print('All files in directory:', '\n', folder_files, '\n')
data_files= []
for file in folder_files: 
     if file.endswith('.csv'):
        data_files.append(file)
print('.csv files:', '\n', data_files, '\n')

'''
This was my initial attempt using a dictionary, so that an example key would be 
"tmdb_movies" and the value would be "tmdb.movies.csv".

placeholder = {file[:-4]:file for file in data_files} This was my initial attempt using a dictionary
for key, value  in placeholder:
    key  = pd.read_csv(path + '/' + value)
    
 '''  
placeholder = [file[:-4].replace('.', '_') for file in data_files]
print('renamed files:', '\n', placeholder)
for index in range(len(placeholder)):
    placeholder[index]  = pd.read_csv(path + '/' + data_files[index])

All files in directory:
 ['.DS_Store', '~$related imdb and finance data.xlsx', 'tmdb.movies.csv', 'imdb.title.crew.csv', 'rt.reviews.tsv', 'tn.movie_budgets.csv', 'imdb.title.ratings.csv', 'importing_data.ipynb', 'imdb.name.basics.csv', 'imdb.title.principals.csv', 'imdb.title.akas.csv', 'related imdb and finance data.xlsx', 'bom.movie_gross.csv', 'imdb.title.basics.csv', 'rt.movie_info.tsv', '.ipynb_checkpoints']

.csv files:
 ['tmdb.movies.csv', 'imdb.title.crew.csv', 'tn.movie_budgets.csv', 'imdb.title.ratings.csv', 'imdb.name.basics.csv', 'imdb.title.principals.csv', 'imdb.title.akas.csv', 'bom.movie_gross.csv', 'imdb.title.basics.csv']

renamed files:
 ['tmdb_movies', 'imdb_title_crew', 'tn_movie_budgets', 'imdb_title_ratings', 'imdb_name_basics', 'imdb_title_principals', 'imdb_title_akas', 'bom_movie_gross', 'imdb_title_basics']

In [169]:
#assigning datasets to variables
tmdb_movies = placeholder[0]
imdb_title_crew = placeholder[1]
tn_movie_budgets = placeholder[2]
imdb_title_ratings = placeholder[3]
imdb_name_basics = placeholder[4]
imdb_title_principals = placeholder[5]
imdb_title_akas = placeholder[6]
bom_movie_gross = placeholder[7]
imdb_title_basics = placeholder[8]

In [168]:
# dataframes ={}
# for key in placeholder.keys():
#     data = placeholder[key][:-4].replace('.', '_')
#     dataframes[data] = placeholder[key]
# print('dictionary of dataframes:', '\n', dataframes)

In [166]:
# for key, value in dataframes.items():
#     print('first line of', dataframes[key],':')
#     key  = pd.read_csv(path + '/' + value)
#     print(key.head(0), '\n')
# return key

In [167]:
# dataframes ={}
# for key in placeholder.keys():
#     data = placeholder[key].replace('.', '_')
#     dataframes[data] = placeholder[key]
# print(dataframes)

In [204]:
# print(tmdb_movies.info(),'\n')

# print(tmdb_movies.describe(),'\n')

# for col in tmdb_movies.columns:
#     print(f"top 5 values: {col}",'\n',tmdb_movies[col].sort_values().head(5),'\n''\n')
#     print(f"bottom values: {col}", '\n', tmdb_movies[col].sort_values(ascending=False).head(5),'\n''\n')

# duplicates = tmdb_movies[tmdb_movies.duplicated()]
# print('number of duplicate rows', len(duplicates),'\n')
# print('sample of duplicates rows:',duplicates.head(),'\n')

# duplicates_ids = tmdb_movies[tmdb_movies.duplicated(subset='id')]
# print('number of duplicate ids:',len(duplicates_ids),'\n')
# print('sample of duplicates rows:',duplicates_ids.head(),'\n')

# for col in tmdb_movies.columns:
#     print(col, '\n', tmdb_movies[col].value_counts(normalize=True).head(), '\n\n')

In [209]:
for index in range(len(placeholder)):
    print("index:", index)
    print(placeholder[index].info(),'\n')
    print(placeholder[index].describe(),'\n')

    for col in placeholder[index].columns:
        print(f"top 5 values: {col}",'\n',placeholder[index][col].sort_values().head(5),'\n''\n')
        print(f"bottom values: {col}", '\n', placeholder[index][col].sort_values(ascending=False).head(5),'\n''\n')

    duplicates = placeholder[index][placeholder[index].duplicated()]
    print('number of duplicate rows', len(duplicates),'\n')
    print('sample of duplicates rows:',duplicates.head(),'\n')

    duplicates_ids = placeholder[index][placeholder[index].duplicated(subset='id')]
    print('number of duplicate ids:',len(duplicates_ids),'\n')
    print('sample of duplicates rows:',duplicates_ids.head(),'\n')

    for col in placeholder[index].columns:
        print(col, '\n', tmdb_movies[col].value_counts(normalize=True).head(), '\n\n')

index: 0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26517 entries, 0 to 26516
Data columns (total 10 columns):
Unnamed: 0           26517 non-null int64
genre_ids            26517 non-null object
id                   26517 non-null int64
original_language    26517 non-null object
original_title       26517 non-null object
popularity           26517 non-null float64
release_date         26517 non-null object
title                26517 non-null object
vote_average         26517 non-null float64
vote_count           26517 non-null int64
dtypes: float64(2), int64(3), object(5)
memory usage: 2.0+ MB
None

        Unnamed: 0             id    popularity  vote_average    vote_count
count  26517.00000   26517.000000  26517.000000  26517.000000  26517.000000
mean   13258.00000  295050.153260      3.130912      5.991281    194.224837
std     7654.94288  153661.615648      4.355229      1.852946    960.961095
min        0.00000      27.000000      0.600000      0.000000      1.000000
25%     6629.00000  157851.000000      0.600000      5.000000      2.000000
50%    13258.00000  309581.000000      1.374000      6.000000      5.000000
75%    19887.00000  419542.000000      3.694000      7.000000     28.000000
max    26516.00000  608444.000000     80.773000     10.000000  22186.000000

top 5 values: Unnamed: 0
 0    0
1    1
2    2
3    3
4    4
Name: Unnamed: 0, dtype: int64


bottom values: Unnamed: 0
 26516    26516
26515    26515
26514    26514
26513    26513
26512    26512
Name: Unnamed: 0, dtype: int64


top 5 values: genre_ids
 9992         [10402, 10749, 18]
11735        [10402, 10749, 18]
17813    [10402, 10749, 35, 18]
14538    [10402, 10749, 35, 18]
8527     [10402, 10749, 35, 18]
Name: genre_ids, dtype: object


bottom values: genre_ids
 17242    []
5094     []
12774    []
5060     []
12757    []
Name: genre_ids, dtype: object


top 5 values: id
 117      27
23872    62
2510     90
11109    93
32       95
Name: id, dtype: int64


bottom values: id
 25582    608444
25922    608079
26107    607777
15496    607721
26037    607044
Name: id, dtype: int64


top 5 values: original_language
 20189    ab
16839    ab
18652    ab
4505     ab
18972    ab
Name: original_language, dtype: object


bottom values: original_language
 11793    zh
17054    zh
13823    zh
25569    zh
8798     zh
Name: original_language, dtype: object


top 5 values: original_title
 26355                              "BLESSED"
7815     "Legitimate Rape" Pharmaceutical Ad
12812                     "cherry" - Supreme
577                      #1 Cheerleader Camp
16037                           #ALLMYMOVIES
Name: original_title, dtype: object


bottom values: original_title
 7955     후궁: 제왕의 첩
2587            황해
2179           황산벌
10119     해양경찰 마르코
3276           하하하
Name: original_title, dtype: object


top 5 values: popularity
 13258    0.6
11010    0.6
11011    0.6
11012    0.6
11013    0.6
Name: popularity, dtype: float64


bottom values: popularity
 23811    80.773
11019    78.123
23812    60.534
11020    53.783
5179     50.289
Name: popularity, dtype: float64


top 5 values: release_date
 14335    1930-04-29
21758    1933-01-21
3580     1936-02-27
26345    1939-01-19
11192    1946-12-25
Name: release_date, dtype: object


bottom values: release_date
 26057    2020-12-25
24265    2019-06-28
24892    2019-06-28
24003    2019-05-17
24819    2019-05-17
Name: release_date, dtype: object


top 5 values: title
 26355                              "BLESSED"
7815     "Legitimate Rape" Pharmaceutical Ad
12812                     "cherry" - Supreme
577                      #1 Cheerleader Camp
16037                           #ALLMYMOVIES
Name: title, dtype: object


bottom values: title
 10119               해양경찰 마르코
26106             유병재: B의 농담
26267                번개맨의 비밀
26292    마음의 소리 스페셜 1-효! 크러쉬
5961                  纽约客@上海
Name: title, dtype: object


top 5 values: vote_average
 26516    0.0
22576    0.0
20616    0.0
20615    0.0
20614    0.0
Name: vote_average, dtype: float64


bottom values: vote_average
 13258    10.0
25323    10.0
7068     10.0
7067     10.0
7066     10.0
Name: vote_average, dtype: float64


top 5 values: vote_count
 13258    1
13386    1
13387    1
13389    1
13390    1
Name: vote_count, dtype: int64


bottom values: vote_count
 4        22186
17383    20175
5179     19673
6        18676
11032    18597
Name: vote_count, dtype: int64


number of duplicate rows 0

sample of duplicates rows: Empty DataFrame
Columns: [Unnamed: 0, genre_ids, id, original_language, original_title, popularity, release_date, title, vote_average, vote_count]
Index: []

Unnamed: 0
 2047     0.000038
5448     0.000038
3371     0.000038
13612    0.000038
15661    0.000038
Name: Unnamed: 0, dtype: float64


genre_ids
 [99]    0.139533
[]      0.093487
[18]    0.085530
[35]    0.062601
[27]    0.043180
Name: genre_ids, dtype: float64


id
 292086    0.000113
463839    0.000113
11976     0.000113
391872    0.000113
416572    0.000113
Name: id, dtype: float64


original_language
 en    0.878342
fr    0.019120
es    0.017159
ru    0.011238
ja    0.009994
Name: original_language, dtype: float64


original_title
 Eden             0.000264
Home             0.000226
Lucky            0.000189
Truth or Dare    0.000189
Aftermath        0.000189
Name: original_title, dtype: float64


popularity
 0.600    0.265377
1.400    0.024475
0.840    0.022137
0.624    0.003922
0.625    0.003469
Name: popularity, dtype: float64


release_date
 2010-01-01    0.010144
2011-01-01    0.007542
2012-01-01    0.005845
2014-01-01    0.005845
2013-01-01    0.005468
Name: release_date, dtype: float64


title
 Eden             0.000264
Home             0.000264
Legend           0.000189
Truth or Dare    0.000189
The Box          0.000189
Name: title, dtype: float64


vote_average
 6.0     0.073161
7.0     0.058830
5.0     0.056040
10.0    0.047215
8.0     0.046423
Name: vote_average, dtype: float64


vote_count
 1    0.246672
2    0.114794
3    0.066259
4    0.050798
5    0.036543
Name: vote_count, dtype: float64


index: 1
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 146144 entries, 0 to 146143
Data columns (total 3 columns):
tconst       146144 non-null object
directors    140417 non-null object
writers      110261 non-null object
dtypes: object(3)
memory usage: 3.3+ MB
None

           tconst  directors    writers
count      146144     140417     110261
unique     146144      98525      91920
top     tt3856638  nm3266654  nm0000636
freq            1         62         80

top 5 values: tconst
 111344    tt0063540
74754     tt0066787
33939     tt0069049
4057      tt0069204
125704    tt0100275
Name: tconst, dtype: object


bottom values: tconst
 64745    tt9916754
10772    tt9916730
72320    tt9916706
51800    tt9916622
64744    tt9916538
Name: tconst, dtype: object


top 5 values: directors
 33939     nm0000080
36661     nm0000095
103049    nm0000095
66061     nm0000095
88601     nm0000095
Name: directors, dtype: object


bottom values: directors
 59895                         nm9993573
106053    nm9993380,nm9993379,nm9993381
16856                         nm9992906
91618                         nm9992905
146055                        nm9992900
Name: directors, dtype: object


top 5 values: writers
 87916     nm0000041,nm0368074,nm0644823,nm4446305,nm0921013
33939                                   nm0000080,nm0462648
141533                                            nm0000095
9724                                              nm0000095
88601                                             nm0000095
Name: writers, dtype: object


bottom values: writers
 59895               nm9993573
106053    nm9993380,nm9993379
16856               nm9992906
146055    nm9992900,nm9992899
89388               nm9992590
Name: writers, dtype: object


number of duplicate rows 0

sample of duplicates rows: Empty DataFrame
Columns: [tconst, directors, writers]
Index: []

KeyError: 'tconst'